///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Perromart
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PerromartRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("73842910-c644-49cd-96ec-017afee23e0d")]
    public partial class PerromartRepository : RepoGenBaseFolder
    {
        static PerromartRepository instance = new PerromartRepository();
        PerromartRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        PerromartRepositoryFolders.PerrovetsYourFriendlyVetClinicAtAppFolder _perrovetsyourfriendlyvetclinicat;

        /// <summary>
        /// Gets the singleton class instance representing the PerromartRepository element repository.
        /// </summary>
        [RepositoryFolder("73842910-c644-49cd-96ec-017afee23e0d")]
        public static PerromartRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PerromartRepository() 
            : base("PerromartRepository", "/", null, 0, false, "73842910-c644-49cd-96ec-017afee23e0d", ".\\RepositoryImages\\PerromartRepository73842910.rximgres")
        {
            _applicationundertest = new PerromartRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _perrovetsyourfriendlyvetclinicat = new PerromartRepositoryFolders.PerrovetsYourFriendlyVetClinicAtAppFolder(this);
        }

#region Variables

        string _ProductNaame = "";

        /// <summary>
        /// Gets or sets the value of variable ProductNaame.
        /// </summary>
        [TestVariable("f7b8ae05-a4b4-4d90-bda9-773ded5061a3")]
        public string ProductNaame
        {
            get { return _ProductNaame; }
            set { _ProductNaame = value; }
        }

        string _ProductName = "";

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("e5e3b2f4-052e-4c37-a537-3c788c8cf99e")]
        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

        string _Product = "";

        /// <summary>
        /// Gets or sets the value of variable Product.
        /// </summary>
        [TestVariable("90da5f34-171e-4549-903f-bca454d8a4d7")]
        public string Product
        {
            get { return _Product; }
            set { _Product = value; }
        }

        string _item = "";

        /// <summary>
        /// Gets or sets the value of variable item.
        /// </summary>
        [TestVariable("849b6594-8092-4626-a50a-743feb7f4b50")]
        public string item
        {
            get { return _item; }
            set { _item = value; }
        }

        string _ArticleName = "";

        /// <summary>
        /// Gets or sets the value of variable ArticleName.
        /// </summary>
        [TestVariable("1bb5acb3-3309-4712-895e-b451c35be08b")]
        public string ArticleName
        {
            get { return _ArticleName; }
            set { _ArticleName = value; }
        }

        string _text = "";

        /// <summary>
        /// Gets or sets the value of variable text.
        /// </summary>
        [TestVariable("2d056f7e-908a-4ee4-aba9-7ac6c08e788e")]
        public string text
        {
            get { return _text; }
            set { _text = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("73842910-c644-49cd-96ec-017afee23e0d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("92110ae9-7342-4a8c-86c1-0ea8a48d23ef")]
        public virtual PerromartRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The PerrovetsYourFriendlyVetClinicAt folder.
        /// </summary>
        [RepositoryFolder("f523fff5-e4ba-4d9d-8534-ec0399c69389")]
        public virtual PerromartRepositoryFolders.PerrovetsYourFriendlyVetClinicAtAppFolder PerrovetsYourFriendlyVetClinicAt
        {
            get { return _perrovetsyourfriendlyvetclinicat; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PerromartRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("92110ae9-7342-4a8c-86c1-0ea8a48d23ef")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            PerromartRepositoryFolders.HomePageUIFolder _homepageui;
            PerromartRepositoryFolders.LoginPageUIFolder _loginpageui;
            PerromartRepositoryFolders.CollectionPageUIFolder _collectionpageui;
            PerromartRepositoryFolders.FavPageUIFolder _favpageui;
            PerromartRepositoryFolders.PerrovetPageUIFolder _perrovetpageui;
            PerromartRepositoryFolders.MyPetPageUIFolder _mypetpageui;
            PerromartRepositoryFolders.MyProfilePageUIFolder _myprofilepageui;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='perromart.com.sg']", parentFolder, 30000, null, false, "92110ae9-7342-4a8c-86c1-0ea8a48d23ef", "")
            {
                _homepageui = new PerromartRepositoryFolders.HomePageUIFolder(this);
                _loginpageui = new PerromartRepositoryFolders.LoginPageUIFolder(this);
                _collectionpageui = new PerromartRepositoryFolders.CollectionPageUIFolder(this);
                _favpageui = new PerromartRepositoryFolders.FavPageUIFolder(this);
                _perrovetpageui = new PerromartRepositoryFolders.PerrovetPageUIFolder(this);
                _mypetpageui = new PerromartRepositoryFolders.MyPetPageUIFolder(this);
                _myprofilepageui = new PerromartRepositoryFolders.MyProfilePageUIFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("92110ae9-7342-4a8c-86c1-0ea8a48d23ef")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("92110ae9-7342-4a8c-86c1-0ea8a48d23ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePageUI folder.
            /// </summary>
            [RepositoryFolder("5c81a402-9e57-4f2c-9c70-4d8f2f5e9525")]
            public virtual PerromartRepositoryFolders.HomePageUIFolder HomePageUI
            {
                get { return _homepageui; }
            }

            /// <summary>
            /// The LoginPageUI folder.
            /// </summary>
            [RepositoryFolder("7a35b0fc-c20a-46b1-9b1e-d2d098ec516d")]
            public virtual PerromartRepositoryFolders.LoginPageUIFolder LoginPageUI
            {
                get { return _loginpageui; }
            }

            /// <summary>
            /// The CollectionPageUI folder.
            /// </summary>
            [RepositoryFolder("4a3314ad-4d78-40a6-afc2-8374fc7f86f2")]
            public virtual PerromartRepositoryFolders.CollectionPageUIFolder CollectionPageUI
            {
                get { return _collectionpageui; }
            }

            /// <summary>
            /// The FavPageUI folder.
            /// </summary>
            [RepositoryFolder("77b8745f-17a1-4383-99f0-32b8fe8ea19d")]
            public virtual PerromartRepositoryFolders.FavPageUIFolder FavPageUI
            {
                get { return _favpageui; }
            }

            /// <summary>
            /// The PerrovetPageUI folder.
            /// </summary>
            [RepositoryFolder("6841dc9e-64c2-4857-a66e-d0a4ce655f47")]
            public virtual PerromartRepositoryFolders.PerrovetPageUIFolder PerrovetPageUI
            {
                get { return _perrovetpageui; }
            }

            /// <summary>
            /// The MyPetPageUI folder.
            /// </summary>
            [RepositoryFolder("3f2ad877-1a2a-4f07-a9ea-bbae9e23a49f")]
            public virtual PerromartRepositoryFolders.MyPetPageUIFolder MyPetPageUI
            {
                get { return _mypetpageui; }
            }

            /// <summary>
            /// The MyProfilePageUI folder.
            /// </summary>
            [RepositoryFolder("371fb832-7099-4079-8e7b-082049c2933c")]
            public virtual PerromartRepositoryFolders.MyProfilePageUIFolder MyProfilePageUI
            {
                get { return _myprofilepageui; }
            }
        }

        /// <summary>
        /// The HomePageUIFolder folder.
        /// </summary>
        [RepositoryFolder("5c81a402-9e57-4f2c-9c70-4d8f2f5e9525")]
        public partial class HomePageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconclosepopupInfo;
            RepoItemInfo _iconloginInfo;
            RepoItemInfo _txtsearchInfo;
            RepoItemInfo _btnfavlistInfo;
            RepoItemInfo _btnperrovetInfo;
            RepoItemInfo _icondropdownInfo;
            RepoItemInfo _lblitemInfo;

            /// <summary>
            /// Creates a new HomePageUI  folder.
            /// </summary>
            public HomePageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePageUI", "", parentFolder, 0, null, false, "5c81a402-9e57-4f2c-9c70-4d8f2f5e9525", "")
            {
                _iconclosepopupInfo = new RepoItemInfo(this, "iconClosePopup", ".//button[@tabindex='0']//*[@role='img']", ".//tag[@tagname='circle']", 30000, null, "e952efa2-1508-4043-b36c-f0bc1778c932");
                _iconloginInfo = new RepoItemInfo(this, "IconLogin", ".//*[@class~'Nav_nonLogin']//*[@class~'Nav_nonLoginText']", "element", 30000, null, "dd69b9a3-e9c0-4548-89ee-3dee259a6e57");
                _txtsearchInfo = new RepoItemInfo(this, "txtSearch", ".//*[@class='navbar-nav']//input", ".//div[#'__next']//input[@type='text']", 30000, null, "be645859-771d-4134-91c5-33d8a384c92d");
                _btnfavlistInfo = new RepoItemInfo(this, "btnFavList", ".//*[@class~'justify-content-between']//div[@class~'align-items-center']", "element", 30000, null, "f9b7d00d-5b39-4037-8cb6-a5245f98ea0e");
                _btnperrovetInfo = new RepoItemInfo(this, "btnPerrovet", ".//*[@class~'Nav_navBar']//a[text()='perrovets']", "element", 30000, null, "db5a8603-e78c-48fc-aea3-74fa727d039c");
                _icondropdownInfo = new RepoItemInfo(this, "iconDropdown", ".//*[@id='dropdown-basic-nav']//*", "element", 30000, null, "f716d9dc-18a2-44ec-9210-11634f1049be");
                _lblitemInfo = new RepoItemInfo(this, "lblItem", ".//a[text()=$item]", "", 30000, null, "2510cf7a-1fda-4ba3-966e-6fc4cb7f16d4");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c81a402-9e57-4f2c-9c70-4d8f2f5e9525")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The iconClosePopup item.
            /// </summary>
            [RepositoryItem("e952efa2-1508-4043-b36c-f0bc1778c932")]
            public virtual Ranorex.Unknown iconClosePopup
            {
                get
                {
                    return _iconclosepopupInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The iconClosePopup item info.
            /// </summary>
            [RepositoryItemInfo("e952efa2-1508-4043-b36c-f0bc1778c932")]
            public virtual RepoItemInfo iconClosePopupInfo
            {
                get
                {
                    return _iconclosepopupInfo;
                }
            }

            /// <summary>
            /// The IconLogin item.
            /// </summary>
            [RepositoryItem("dd69b9a3-e9c0-4548-89ee-3dee259a6e57")]
            public virtual Ranorex.Unknown IconLogin
            {
                get
                {
                    return _iconloginInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IconLogin item info.
            /// </summary>
            [RepositoryItemInfo("dd69b9a3-e9c0-4548-89ee-3dee259a6e57")]
            public virtual RepoItemInfo IconLoginInfo
            {
                get
                {
                    return _iconloginInfo;
                }
            }

            /// <summary>
            /// The txtSearch item.
            /// </summary>
            [RepositoryItem("be645859-771d-4134-91c5-33d8a384c92d")]
            public virtual Ranorex.InputTag txtSearch
            {
                get
                {
                    return _txtsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtSearch item info.
            /// </summary>
            [RepositoryItemInfo("be645859-771d-4134-91c5-33d8a384c92d")]
            public virtual RepoItemInfo txtSearchInfo
            {
                get
                {
                    return _txtsearchInfo;
                }
            }

            /// <summary>
            /// The btnFavList item.
            /// </summary>
            [RepositoryItem("f9b7d00d-5b39-4037-8cb6-a5245f98ea0e")]
            public virtual Ranorex.DivTag btnFavList
            {
                get
                {
                    return _btnfavlistInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The btnFavList item info.
            /// </summary>
            [RepositoryItemInfo("f9b7d00d-5b39-4037-8cb6-a5245f98ea0e")]
            public virtual RepoItemInfo btnFavListInfo
            {
                get
                {
                    return _btnfavlistInfo;
                }
            }

            /// <summary>
            /// The btnPerrovet item.
            /// </summary>
            [RepositoryItem("db5a8603-e78c-48fc-aea3-74fa727d039c")]
            public virtual Ranorex.ATag btnPerrovet
            {
                get
                {
                    return _btnperrovetInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnPerrovet item info.
            /// </summary>
            [RepositoryItemInfo("db5a8603-e78c-48fc-aea3-74fa727d039c")]
            public virtual RepoItemInfo btnPerrovetInfo
            {
                get
                {
                    return _btnperrovetInfo;
                }
            }

            /// <summary>
            /// The iconDropdown item.
            /// </summary>
            [RepositoryItem("f716d9dc-18a2-44ec-9210-11634f1049be")]
            public virtual Ranorex.Unknown iconDropdown
            {
                get
                {
                    return _icondropdownInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The iconDropdown item info.
            /// </summary>
            [RepositoryItemInfo("f716d9dc-18a2-44ec-9210-11634f1049be")]
            public virtual RepoItemInfo iconDropdownInfo
            {
                get
                {
                    return _icondropdownInfo;
                }
            }

            /// <summary>
            /// The lblItem item.
            /// </summary>
            [RepositoryItem("2510cf7a-1fda-4ba3-966e-6fc4cb7f16d4")]
            public virtual Ranorex.ATag lblItem
            {
                get
                {
                    return _lblitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lblItem item info.
            /// </summary>
            [RepositoryItemInfo("2510cf7a-1fda-4ba3-966e-6fc4cb7f16d4")]
            public virtual RepoItemInfo lblItemInfo
            {
                get
                {
                    return _lblitemInfo;
                }
            }
        }

        /// <summary>
        /// The LoginPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("7a35b0fc-c20a-46b1-9b1e-d2d098ec516d")]
        public partial class LoginPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _signinInfo;
            RepoItemInfo _txtemailInfo;
            RepoItemInfo _txtpasswordInfo;

            /// <summary>
            /// Creates a new LoginPageUI  folder.
            /// </summary>
            public LoginPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPageUI", "", parentFolder, 0, null, false, "7a35b0fc-c20a-46b1-9b1e-d2d098ec516d", "")
            {
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//*[@type='submit']", ".//div[#'__next']//button[@innertext='Sign In']", 30000, null, "a816a62f-b4d5-4a1e-8f41-c7ef93f45a0c");
                _txtemailInfo = new RepoItemInfo(this, "txtEmail", ".//div[@class~'login_formGroup']//input[@type='text']", ".//div[#'__next']//input[@type='text']", 30000, null, "5716ef51-2560-4cea-b30b-0b423b3446ed");
                _txtpasswordInfo = new RepoItemInfo(this, "txtPassword", ".//div[@class~'login_formGroup']//input[@type='password']", ".//div[#'__next']//input[@type='password']", 30000, null, "5cf603a4-92bf-4797-939f-9a3dc5b072a5");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a35b0fc-c20a-46b1-9b1e-d2d098ec516d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("a816a62f-b4d5-4a1e-8f41-c7ef93f45a0c")]
            public virtual Ranorex.Unknown SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("a816a62f-b4d5-4a1e-8f41-c7ef93f45a0c")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The txtEmail item.
            /// </summary>
            [RepositoryItem("5716ef51-2560-4cea-b30b-0b423b3446ed")]
            public virtual Ranorex.InputTag txtEmail
            {
                get
                {
                    return _txtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtEmail item info.
            /// </summary>
            [RepositoryItemInfo("5716ef51-2560-4cea-b30b-0b423b3446ed")]
            public virtual RepoItemInfo txtEmailInfo
            {
                get
                {
                    return _txtemailInfo;
                }
            }

            /// <summary>
            /// The txtPassword item.
            /// </summary>
            [RepositoryItem("5cf603a4-92bf-4797-939f-9a3dc5b072a5")]
            public virtual Ranorex.InputTag txtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPassword item info.
            /// </summary>
            [RepositoryItemInfo("5cf603a4-92bf-4797-939f-9a3dc5b072a5")]
            public virtual RepoItemInfo txtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }
        }

        /// <summary>
        /// The CollectionPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("4a3314ad-4d78-40a6-afc2-8374fc7f86f2")]
        public partial class CollectionPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productinresultInfo;
            RepoItemInfo _msgaddedtofavInfo;
            RepoItemInfo _msgremovefromfavInfo;
            RepoItemInfo _btnaddtofavInfo;

            /// <summary>
            /// Creates a new CollectionPageUI  folder.
            /// </summary>
            public CollectionPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("CollectionPageUI", "", parentFolder, 0, null, false, "4a3314ad-4d78-40a6-afc2-8374fc7f86f2", "")
            {
                _productinresultInfo = new RepoItemInfo(this, "ProductInResult", ".//*[@class~'productsDisplay']//*[text()=$Product]", "", 30000, null, "cde01630-9d6b-486e-a016-0e4c33154aec");
                _msgaddedtofavInfo = new RepoItemInfo(this, "MSGAddedToFav", ".//*[@class~'ps-3']", "element", 30000, null, "cb5666e3-5675-45c7-a70d-0dc5b48fc606");
                _msgremovefromfavInfo = new RepoItemInfo(this, "MSGRemoveFromFav", ".//*[text()='Removed from favourites']", "element", 30000, null, "34e44e06-62fb-46de-a105-232f09d56fc2");
                _btnaddtofavInfo = new RepoItemInfo(this, "btnAddToFav", ".//*[text()=$product]/../..//*[@class~'wishlistIconDesktop']", "", 30000, null, "dca83d7a-4031-43d1-93e3-689cf32cf558");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a3314ad-4d78-40a6-afc2-8374fc7f86f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductInResult item.
            /// </summary>
            [RepositoryItem("cde01630-9d6b-486e-a016-0e4c33154aec")]
            public virtual Ranorex.Unknown ProductInResult
            {
                get
                {
                    return _productinresultInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ProductInResult item info.
            /// </summary>
            [RepositoryItemInfo("cde01630-9d6b-486e-a016-0e4c33154aec")]
            public virtual RepoItemInfo ProductInResultInfo
            {
                get
                {
                    return _productinresultInfo;
                }
            }

            /// <summary>
            /// The MSGAddedToFav item.
            /// </summary>
            [RepositoryItem("cb5666e3-5675-45c7-a70d-0dc5b48fc606")]
            public virtual Ranorex.Unknown MSGAddedToFav
            {
                get
                {
                    return _msgaddedtofavInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MSGAddedToFav item info.
            /// </summary>
            [RepositoryItemInfo("cb5666e3-5675-45c7-a70d-0dc5b48fc606")]
            public virtual RepoItemInfo MSGAddedToFavInfo
            {
                get
                {
                    return _msgaddedtofavInfo;
                }
            }

            /// <summary>
            /// The MSGRemoveFromFav item.
            /// </summary>
            [RepositoryItem("34e44e06-62fb-46de-a105-232f09d56fc2")]
            public virtual Ranorex.Unknown MSGRemoveFromFav
            {
                get
                {
                    return _msgremovefromfavInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MSGRemoveFromFav item info.
            /// </summary>
            [RepositoryItemInfo("34e44e06-62fb-46de-a105-232f09d56fc2")]
            public virtual RepoItemInfo MSGRemoveFromFavInfo
            {
                get
                {
                    return _msgremovefromfavInfo;
                }
            }

            /// <summary>
            /// The btnAddToFav item.
            /// </summary>
            [RepositoryItem("dca83d7a-4031-43d1-93e3-689cf32cf558")]
            public virtual Ranorex.Unknown btnAddToFav
            {
                get
                {
                    return _btnaddtofavInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnAddToFav item info.
            /// </summary>
            [RepositoryItemInfo("dca83d7a-4031-43d1-93e3-689cf32cf558")]
            public virtual RepoItemInfo btnAddToFavInfo
            {
                get
                {
                    return _btnaddtofavInfo;
                }
            }
        }

        /// <summary>
        /// The FavPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("77b8745f-17a1-4383-99f0-32b8fe8ea19d")]
        public partial class FavPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productinfavInfo;

            /// <summary>
            /// Creates a new FavPageUI  folder.
            /// </summary>
            public FavPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("FavPageUI", "", parentFolder, 0, null, false, "77b8745f-17a1-4383-99f0-32b8fe8ea19d", "")
            {
                _productinfavInfo = new RepoItemInfo(this, "ProductInFav", ".//div[@class~'container']//*[text()=$ProductName]", "element", 30000, null, "d739ce7e-6a74-41c3-bbbe-b3b4565f9530");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77b8745f-17a1-4383-99f0-32b8fe8ea19d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductInFav item.
            /// </summary>
            [RepositoryItem("d739ce7e-6a74-41c3-bbbe-b3b4565f9530")]
            public virtual Ranorex.Unknown ProductInFav
            {
                get
                {
                    return _productinfavInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ProductInFav item info.
            /// </summary>
            [RepositoryItemInfo("d739ce7e-6a74-41c3-bbbe-b3b4565f9530")]
            public virtual RepoItemInfo ProductInFavInfo
            {
                get
                {
                    return _productinfavInfo;
                }
            }
        }

        /// <summary>
        /// The PerrovetPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("6841dc9e-64c2-4857-a66e-d0a4ce655f47")]
        public partial class PerrovetPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btncallnowInfo;

            /// <summary>
            /// Creates a new PerrovetPageUI  folder.
            /// </summary>
            public PerrovetPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("PerrovetPageUI", "", parentFolder, 0, null, false, "6841dc9e-64c2-4857-a66e-d0a4ce655f47", "")
            {
                _btncallnowInfo = new RepoItemInfo(this, "btnCallNow", ".//*[@class='w-container']//*[@class='button']", "element", 30000, null, "59fcd701-0251-4602-a0f7-d6e8cc3f3f61");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6841dc9e-64c2-4857-a66e-d0a4ce655f47")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnCallNow item.
            /// </summary>
            [RepositoryItem("59fcd701-0251-4602-a0f7-d6e8cc3f3f61")]
            public virtual Ranorex.Unknown btnCallNow
            {
                get
                {
                    return _btncallnowInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnCallNow item info.
            /// </summary>
            [RepositoryItemInfo("59fcd701-0251-4602-a0f7-d6e8cc3f3f61")]
            public virtual RepoItemInfo btnCallNowInfo
            {
                get
                {
                    return _btncallnowInfo;
                }
            }
        }

        /// <summary>
        /// The MyPetPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("3f2ad877-1a2a-4f07-a9ea-bbae9e23a49f")]
        public partial class MyPetPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaddpetInfo;

            /// <summary>
            /// Creates a new MyPetPageUI  folder.
            /// </summary>
            public MyPetPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("MyPetPageUI", "", parentFolder, 0, null, false, "3f2ad877-1a2a-4f07-a9ea-bbae9e23a49f", "")
            {
                _btnaddpetInfo = new RepoItemInfo(this, "btnAddPet", ".//*[@class~'main_continueShoppingbutton']", "element", 30000, null, "88ad6608-0065-45f6-b306-a3026b217ba2");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3f2ad877-1a2a-4f07-a9ea-bbae9e23a49f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAddPet item.
            /// </summary>
            [RepositoryItem("88ad6608-0065-45f6-b306-a3026b217ba2")]
            public virtual Ranorex.Unknown btnAddPet
            {
                get
                {
                    return _btnaddpetInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnAddPet item info.
            /// </summary>
            [RepositoryItemInfo("88ad6608-0065-45f6-b306-a3026b217ba2")]
            public virtual RepoItemInfo btnAddPetInfo
            {
                get
                {
                    return _btnaddpetInfo;
                }
            }
        }

        /// <summary>
        /// The MyProfilePageUIFolder folder.
        /// </summary>
        [RepositoryFolder("371fb832-7099-4079-8e7b-082049c2933c")]
        public partial class MyProfilePageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconeditInfo;
            RepoItemInfo _txtfirstnameInfo;
            RepoItemInfo _txtlastnameInfo;
            RepoItemInfo _btnsaveInfo;
            RepoItemInfo _txtnameInfo;
            RepoItemInfo _profileimageInfo;
            RepoItemInfo _lblusernameInfo;
            RepoItemInfo _lbluserimageInfo;

            /// <summary>
            /// Creates a new MyProfilePageUI  folder.
            /// </summary>
            public MyProfilePageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("MyProfilePageUI", "", parentFolder, 0, null, false, "371fb832-7099-4079-8e7b-082049c2933c", "")
            {
                _iconeditInfo = new RepoItemInfo(this, "iconEdit", ".//*[@class='mx-2']//*", "element", 30000, null, "9cec6fb5-92ef-4d0a-8a1e-649cfe57309b");
                _txtfirstnameInfo = new RepoItemInfo(this, "txtFirstName", ".//*[@name='firstName']", "element", 30000, null, "51eaaeeb-b242-4512-8a38-47df83f25031");
                _txtlastnameInfo = new RepoItemInfo(this, "txtLastName", ".//*[@name='lastName']", "element", 30000, null, "6cf5a7ff-1258-4a6d-9970-80bcdb2aed8b");
                _btnsaveInfo = new RepoItemInfo(this, "btnSave", ".//*[@class~'mx-2']//*[text()='Save Changes']", "element", 30000, null, "58914fd4-6fc0-4e9c-97f8-90f5ade0b9c7");
                _txtnameInfo = new RepoItemInfo(this, "txtName", ".//*[@class~'d-sm-block']//*[@class~'InfoStyle_Detail']/*[@class~'InfoStyle_data']", "element", 30000, null, "1fc6cc10-94fd-4ce5-a992-f7b08e3547ed");
                _profileimageInfo = new RepoItemInfo(this, "ProfileImage", ".//*[@class='profileImage']/*", "element", 30000, null, "75384b87-a2b6-4b97-b895-09c6acae814c");
                _lblusernameInfo = new RepoItemInfo(this, "lblUserName", ".//*[@class~'Nav_userName']", "element", 30000, null, "afd9765b-3b64-4343-86d5-a7fc494bccdc");
                _lbluserimageInfo = new RepoItemInfo(this, "lblUserImage", ".//*[@class~'Nav_profile']//*[@class~'Nav_userImg']//p", "element", 30000, null, "b0c86311-b014-4458-b315-445b785b19b4");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("371fb832-7099-4079-8e7b-082049c2933c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The iconEdit item.
            /// </summary>
            [RepositoryItem("9cec6fb5-92ef-4d0a-8a1e-649cfe57309b")]
            public virtual Ranorex.Unknown iconEdit
            {
                get
                {
                    return _iconeditInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The iconEdit item info.
            /// </summary>
            [RepositoryItemInfo("9cec6fb5-92ef-4d0a-8a1e-649cfe57309b")]
            public virtual RepoItemInfo iconEditInfo
            {
                get
                {
                    return _iconeditInfo;
                }
            }

            /// <summary>
            /// The txtFirstName item.
            /// </summary>
            [RepositoryItem("51eaaeeb-b242-4512-8a38-47df83f25031")]
            public virtual Ranorex.Unknown txtFirstName
            {
                get
                {
                    return _txtfirstnameInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The txtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("51eaaeeb-b242-4512-8a38-47df83f25031")]
            public virtual RepoItemInfo txtFirstNameInfo
            {
                get
                {
                    return _txtfirstnameInfo;
                }
            }

            /// <summary>
            /// The txtLastName item.
            /// </summary>
            [RepositoryItem("6cf5a7ff-1258-4a6d-9970-80bcdb2aed8b")]
            public virtual Ranorex.Unknown txtLastName
            {
                get
                {
                    return _txtlastnameInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The txtLastName item info.
            /// </summary>
            [RepositoryItemInfo("6cf5a7ff-1258-4a6d-9970-80bcdb2aed8b")]
            public virtual RepoItemInfo txtLastNameInfo
            {
                get
                {
                    return _txtlastnameInfo;
                }
            }

            /// <summary>
            /// The btnSave item.
            /// </summary>
            [RepositoryItem("58914fd4-6fc0-4e9c-97f8-90f5ade0b9c7")]
            public virtual Ranorex.Unknown btnSave
            {
                get
                {
                    return _btnsaveInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnSave item info.
            /// </summary>
            [RepositoryItemInfo("58914fd4-6fc0-4e9c-97f8-90f5ade0b9c7")]
            public virtual RepoItemInfo btnSaveInfo
            {
                get
                {
                    return _btnsaveInfo;
                }
            }

            /// <summary>
            /// The txtName item.
            /// </summary>
            [RepositoryItem("1fc6cc10-94fd-4ce5-a992-f7b08e3547ed")]
            public virtual Ranorex.Unknown txtName
            {
                get
                {
                    return _txtnameInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The txtName item info.
            /// </summary>
            [RepositoryItemInfo("1fc6cc10-94fd-4ce5-a992-f7b08e3547ed")]
            public virtual RepoItemInfo txtNameInfo
            {
                get
                {
                    return _txtnameInfo;
                }
            }

            /// <summary>
            /// The ProfileImage item.
            /// </summary>
            [RepositoryItem("75384b87-a2b6-4b97-b895-09c6acae814c")]
            public virtual Ranorex.Unknown ProfileImage
            {
                get
                {
                    return _profileimageInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ProfileImage item info.
            /// </summary>
            [RepositoryItemInfo("75384b87-a2b6-4b97-b895-09c6acae814c")]
            public virtual RepoItemInfo ProfileImageInfo
            {
                get
                {
                    return _profileimageInfo;
                }
            }

            /// <summary>
            /// The lblUserName item.
            /// </summary>
            [RepositoryItem("afd9765b-3b64-4343-86d5-a7fc494bccdc")]
            public virtual Ranorex.Unknown lblUserName
            {
                get
                {
                    return _lblusernameInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The lblUserName item info.
            /// </summary>
            [RepositoryItemInfo("afd9765b-3b64-4343-86d5-a7fc494bccdc")]
            public virtual RepoItemInfo lblUserNameInfo
            {
                get
                {
                    return _lblusernameInfo;
                }
            }

            /// <summary>
            /// The lblUserImage item.
            /// </summary>
            [RepositoryItem("b0c86311-b014-4458-b315-445b785b19b4")]
            public virtual Ranorex.PTag lblUserImage
            {
                get
                {
                    return _lbluserimageInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The lblUserImage item info.
            /// </summary>
            [RepositoryItemInfo("b0c86311-b014-4458-b315-445b785b19b4")]
            public virtual RepoItemInfo lblUserImageInfo
            {
                get
                {
                    return _lbluserimageInfo;
                }
            }
        }

        /// <summary>
        /// The PerrovetsYourFriendlyVetClinicAtAppFolder folder.
        /// </summary>
        [RepositoryFolder("f523fff5-e4ba-4d9d-8534-ec0399c69389")]
        public partial class PerrovetsYourFriendlyVetClinicAtAppFolder : RepoGenBaseFolder
        {
            PerromartRepositoryFolders.PerrovetPageUIFolder1 _perrovetpageui;

            /// <summary>
            /// Creates a new PerrovetsYourFriendlyVetClinicAt  folder.
            /// </summary>
            public PerrovetsYourFriendlyVetClinicAtAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PerrovetsYourFriendlyVetClinicAt", "/dom[@domain='www.perrovets.com']", parentFolder, 30000, null, false, "f523fff5-e4ba-4d9d-8534-ec0399c69389", "")
            {
                _perrovetpageui = new PerromartRepositoryFolders.PerrovetPageUIFolder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f523fff5-e4ba-4d9d-8534-ec0399c69389")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f523fff5-e4ba-4d9d-8534-ec0399c69389")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PerrovetPageUI folder.
            /// </summary>
            [RepositoryFolder("25ac14e3-f59f-42fc-bb69-fd9ebbb887e7")]
            public virtual PerromartRepositoryFolders.PerrovetPageUIFolder1 PerrovetPageUI
            {
                get { return _perrovetpageui; }
            }
        }

        /// <summary>
        /// The PerrovetPageUIFolder1 folder.
        /// </summary>
        [RepositoryFolder("25ac14e3-f59f-42fc-bb69-fd9ebbb887e7")]
        public partial class PerrovetPageUIFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _ourblogInfo;
            RepoItemInfo _txtsearchInfo;
            RepoItemInfo _articleInfo;
            RepoItemInfo _contentInfo;

            /// <summary>
            /// Creates a new PerrovetPageUI  folder.
            /// </summary>
            public PerrovetPageUIFolder1(RepoGenBaseFolder parentFolder) :
                    base("PerrovetPageUI", "", parentFolder, 0, null, false, "25ac14e3-f59f-42fc-bb69-fd9ebbb887e7", "")
            {
                _ourblogInfo = new RepoItemInfo(this, "OurBlog", ".//*[@class='tab-link' and text()='Our Blog']", "element", 30000, null, "4b8a3b95-db2a-419e-bdd8-f53add19f2e3");
                _txtsearchInfo = new RepoItemInfo(this, "txtSearch", ".//*[@id='field']", "element", 30000, null, "469c09a8-f3e2-434f-bd06-397734c1709d");
                _articleInfo = new RepoItemInfo(this, "Article", ".//*[text()=$ArticleName]", "element", 30000, null, "333b317e-517d-4f23-86b5-dc3fd94d9742");
                _contentInfo = new RepoItemInfo(this, "Content", ".//*[@class='article-title']/..//*//*[text()~$text]", "element", 30000, null, "11b7c466-02c5-4e71-8424-e65fae5950ae");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("25ac14e3-f59f-42fc-bb69-fd9ebbb887e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OurBlog item.
            /// </summary>
            [RepositoryItem("4b8a3b95-db2a-419e-bdd8-f53add19f2e3")]
            public virtual Ranorex.Unknown OurBlog
            {
                get
                {
                    return _ourblogInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The OurBlog item info.
            /// </summary>
            [RepositoryItemInfo("4b8a3b95-db2a-419e-bdd8-f53add19f2e3")]
            public virtual RepoItemInfo OurBlogInfo
            {
                get
                {
                    return _ourblogInfo;
                }
            }

            /// <summary>
            /// The txtSearch item.
            /// </summary>
            [RepositoryItem("469c09a8-f3e2-434f-bd06-397734c1709d")]
            public virtual Ranorex.Unknown txtSearch
            {
                get
                {
                    return _txtsearchInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The txtSearch item info.
            /// </summary>
            [RepositoryItemInfo("469c09a8-f3e2-434f-bd06-397734c1709d")]
            public virtual RepoItemInfo txtSearchInfo
            {
                get
                {
                    return _txtsearchInfo;
                }
            }

            /// <summary>
            /// The Article item.
            /// </summary>
            [RepositoryItem("333b317e-517d-4f23-86b5-dc3fd94d9742")]
            public virtual Ranorex.Unknown Article
            {
                get
                {
                    return _articleInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Article item info.
            /// </summary>
            [RepositoryItemInfo("333b317e-517d-4f23-86b5-dc3fd94d9742")]
            public virtual RepoItemInfo ArticleInfo
            {
                get
                {
                    return _articleInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("11b7c466-02c5-4e71-8424-e65fae5950ae")]
            public virtual Ranorex.Unknown Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("11b7c466-02c5-4e71-8424-e65fae5950ae")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
