///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Perromart
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchProduct recording.
    /// </summary>
    [TestModule("9fa8fe57-2398-4550-bf49-88bc75c03886", ModuleType.Recording, 1)]
    public partial class SearchProduct : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerromartRepository repository.
        /// </summary>
        public static PerromartRepository repo = PerromartRepository.Instance;

        static SearchProduct instance = new SearchProduct();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchProduct()
        {
            ProductName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchProduct Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("b9b6c631-a9da-425a-860e-a4edd4f8845a")]
        public string ProductName
        {
            get { return repo.ProductName; }
            set { repo.ProductName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HomePageUI.txtSearch' at 334;24.", repo.ApplicationUnderTest.HomePageUI.txtSearchInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HomePageUI.txtSearch.Click("334;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ProductName' with focus on 'ApplicationUnderTest.HomePageUI.txtSearch'.", repo.ApplicationUnderTest.HomePageUI.txtSearchInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.HomePageUI.txtSearch.PressKeys(ProductName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.HomePageUI.txtSearch'.", repo.ApplicationUnderTest.HomePageUI.txtSearchInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.HomePageUI.txtSearch.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
