///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Perromart
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyMSGRemovedFromFav recording.
    /// </summary>
    [TestModule("043472be-b541-499a-9b60-68afc49e402e", ModuleType.Recording, 1)]
    public partial class VerifyMSGRemovedFromFav : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerromartRepository repository.
        /// </summary>
        public static PerromartRepository repo = PerromartRepository.Instance;

        static VerifyMSGRemovedFromFav instance = new VerifyMSGRemovedFromFav();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyMSGRemovedFromFav()
        {
            message = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyMSGRemovedFromFav Instance
        {
            get { return instance; }
        }

#region Variables

        string _message;

        /// <summary>
        /// Gets or sets the value of variable message.
        /// </summary>
        [TestVariable("47bc46b1-d648-44a4-afa4-302002d2aea3")]
        public string message
        {
            get { return _message; }
            set { _message = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Product.
        /// </summary>
        [TestVariable("90da5f34-171e-4549-903f-bca454d8a4d7")]
        public string Product
        {
            get { return repo.Product; }
            set { repo.Product = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CollectionPageUI.btnAddToFav' at Center.", repo.ApplicationUnderTest.CollectionPageUI.btnAddToFavInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.CollectionPageUI.btnAddToFav.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.CollectionPageUI.MSGRemoveFromFav'.", repo.ApplicationUnderTest.CollectionPageUI.MSGRemoveFromFavInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ApplicationUnderTest.CollectionPageUI.MSGRemoveFromFavInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
