///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Perromart
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTextInArticle recording.
    /// </summary>
    [TestModule("855aa8fd-9eda-4fd6-a217-6678b959c964", ModuleType.Recording, 1)]
    public partial class VerifyTextInArticle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PerromartRepository repository.
        /// </summary>
        public static PerromartRepository repo = PerromartRepository.Instance;

        static VerifyTextInArticle instance = new VerifyTextInArticle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTextInArticle()
        {
            Article = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTextInArticle Instance
        {
            get { return instance; }
        }

#region Variables

        string _Article;

        /// <summary>
        /// Gets or sets the value of variable Article.
        /// </summary>
        [TestVariable("f9e18aec-7aec-4b33-9fa8-aa465f2a4cbf")]
        public string Article
        {
            get { return _Article; }
            set { _Article = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ArticleName.
        /// </summary>
        [TestVariable("1bb5acb3-3309-4712-895e-b451c35be08b")]
        public string ArticleName
        {
            get { return repo.ArticleName; }
            set { repo.ArticleName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable text.
        /// </summary>
        [TestVariable("2d056f7e-908a-4ee4-aba9-7ac6c08e788e")]
        public string text
        {
            get { return repo.text; }
            set { repo.text = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.OurBlog'.", repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.OurBlogInfo, new RecordItemIndex(0));
            repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.OurBlog.Focus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.OurBlog' at Center.", repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.OurBlogInfo, new RecordItemIndex(1));
            repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.OurBlog.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Article' with focus on 'PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.txtSearch'.", repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.txtSearchInfo, new RecordItemIndex(2));
            repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.txtSearch.PressKeys(Article);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press with focus on 'PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.txtSearch'.", repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.txtSearchInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.txtSearch);
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.Article' at Center.", repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.ArticleInfo, new RecordItemIndex(4));
            repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.Article.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.Content'.", repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.ContentInfo, new RecordItemIndex(5));
            Validate.Exists(repo.PerrovetsYourFriendlyVetClinicAt.PerrovetPageUI.ContentInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
